[package]
name = "snake-cli"
version = "0.1.0"
authors = ["mattew"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "0.1.0"
rand = "0.7.3"
